eplmp-server/eplmp-server-ejb/pom.xml
eplmp-server/eplmp-server-rest/pom.xml
pom.xml

All description done here:  https://github.com/docdoku/docdoku-plm/issues/1127

Fix SLF4J dependency incorrect bindings. 

---

eplmp-server/eplmp-server-ear/src/main/application/META-INF/glassfish-application.xml
eplmp-server/eplmp-server-ejb/src/main/resources/META-INF/glassfish-ejb-jar.xml

See https://github.com/docdoku/docdoku-plm/issues/1129

Fix JEE role mapping duplicate warning at startup

---

eplmp-core/src/main/java/org/polarsys/eplmp/core/document/DocumentRevision.java
eplmp-core/src/main/java/org/polarsys/eplmp/core/product/PartRevision.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/DocumentBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/DocumentTemplateBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/PartBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/PartTemplateBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/ProductInstanceBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/util/BinaryResourceDownloadResponseBuilder.java

Signed-off-by: Yacine Merghoub <yacine.merghoub@docdoku.com>

No cache control max-age when downloading a working copy

---

eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/util/SearchQueryParser.java

Signed-off-by: Yacine Merghoub <yacine.merghoub@docdoku.com>

Percent issue when searching

---

eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerQueryBuilder.java
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/analyzer-setting.json
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/source-mapping.json

Now advanced search on string keywords is fuzziness and case unsensitive.
Also, unused imports removed.
Note : You have to reindex the old workspaces to benefit from this new feature

case unsensivity plus fuzziness for advanced search 

---

eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/OrganizationResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/OrganizationDTO.java

This modification is necessary to improve organisation-management section of the front-end. It will allow to check if currently logged-in user is owner of his organisation.

#918 Add owner login to OrganizationDTO

---

eplmp-core/src/main/java/org/polarsys/eplmp/core/document/DocumentRevision.java
eplmp-core/src/main/java/org/polarsys/eplmp/core/product/PartRevision.java
eplmp-core/src/main/resources/org/polarsys/eplmp/core/i18n/LocalStrings_en.properties
eplmp-core/src/main/resources/org/polarsys/eplmp/core/i18n/LocalStrings_fr.properties
eplmp-core/src/main/resources/org/polarsys/eplmp/core/i18n/LocalStrings_ru.properties
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/DocumentManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/ProductManagerBean.java

Checking out a revision (part or document) must not be allowed if it's not the latest one.

---

eplmp-core/src/main/java/org/polarsys/eplmp/core/services/IAccountManagerLocal.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/AccountManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/ActivityCheckerInterceptor.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/EffectivityManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/ImporterBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/LOVManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/OrganizationManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/PSFilterManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/TaskManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/UserManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/WebhookManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/WorkflowManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/WorkspaceManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/dao/GCMAccountDAO.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/dao/OrganizationDAO.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/dao/TagDAO.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/dao/UserDAO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/DocumentResource.java

Also some fixes suggested by IDE.
Ref #1165

Some fixes for issues introduced by the DAO injection PR

---

eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/AuthResource.java
eplmp-server/eplmp-server-rest/src/test/java/org/polarsys/eplmp/server/rest/AuthResourceTest.java

A unit test for login service from AuthResource class was create.
AccountDTO returned by the service was corrected in order to display admin field with value 'true' in his json response when admin is connecting.

Correction for issue #1171 

---

eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/AccountResource.java
eplmp-server/eplmp-server-rest/src/test/java/org/polarsys/eplmp/server/rest/AccountResourceTest.java

Issue-1177 was corrected, Now the http response return 'admin' field with right value.

Issue-1177 corrected ( clean version )

---

eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/export/ExcelGenerator.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/ChangeIssuesResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/ChangeOrdersResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/ChangeRequestsResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/TaskResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/converters/ActivityDozerConverter.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/converters/ActivityModelDozerConverter.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/converters/InstanceAttributeDozerConverter.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/converters/InstanceAttributeTemplateDozerConverter.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/ACLDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/ActivityDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/ActivityModelDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/ActivityType.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/InstanceAttributeDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/InstanceAttributeTemplateDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/InstanceAttributeType.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/TaskAction.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/TaskDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/TaskProcessDTO.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/TaskStatus.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/dto/change/ChangeItemDTO.java
eplmp-server/eplmp-server-rest/src/test/java/org/polarsys/eplmp/server/rest/AttributesResourceTest.java
eplmp-server/eplmp-server-rest/src/test/java/org/polarsys/eplmp/server/rest/WorkflowModelResourceTest.java

Correction for issue 1184 ( version 2 )

correction issue-1184 V2

---

eplmp-core/src/main/java/org/polarsys/eplmp/core/configuration/ProductBaseline.java
eplmp-core/src/main/java/org/polarsys/eplmp/core/configuration/ProductConfiguration.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/dao/ProductBaselineDAO.java

related to [issue-43](https://github.com/docdoku/docdoku-web-front/issues/43)

sorted configuration and baseline

---

eplmp-server/eplmp-server-ejb/pom.xml
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/configuration/PSFilterVisitor.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/configuration/PSFilterVisitorTest.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/configuration/filter/LatestCheckedInPSFilterTest.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/configuration/filter/LatestReleasedPSFilterTest.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/configuration/filter/ReleasedPSFilterTest.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/configuration/filter/UpdatePartIterationPSFilterTest.java
pom.xml

new pull request which group all tests implemented in same location.

unit test for visitor and filters

---

eplmp-server/eplmp-server-ejb/pom.xml
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/ConverterBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/geometry/GeometryParser.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/ConverterBeanTest.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/geometry/GeometryParserTest.java

merging work on bounding box parsing

Bounding box: Read converted file without lib

---

eplmp-core/src/main/java/org/polarsys/eplmp/core/product/DateBasedEffectivity.java
eplmp-core/src/main/java/org/polarsys/eplmp/core/product/Effectivity.java
eplmp-core/src/main/java/org/polarsys/eplmp/core/product/LotBasedEffectivity.java
eplmp-core/src/main/java/org/polarsys/eplmp/core/product/SerialNumberBasedEffectivity.java
eplmp-server/eplmp-server-ejb/src/test/java/org/polarsys/eplmp/server/configuration/PSFilterVisitorTest.java

Effectivity TU with serial number filter added.

Create baseline with SN effectivity filter test added

---

eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerQueryBuilder.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/config/IndexerConfig.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/util/IndicesUtils.java
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/common-template.json
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/document-template.json
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/part-template.json

Es index was prefixed with a custom property

ES index update

---

eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/DocumentManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/ProductManagerBean.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/DocumentResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/PartResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/DocumentBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/PartBinaryResource.java

fix of the download of the files in the permalink #1203

PR  Permalink

---

eplmp-core/pom.xml
eplmp-i18n/pom.xml
eplmp-server/eplmp-server-ear/pom.xml
eplmp-server/eplmp-server-ejb/pom.xml
eplmp-server/eplmp-server-ext/pom.xml
eplmp-server/eplmp-server-office-doc/pom.xml
eplmp-server/eplmp-server-rest/pom.xml
eplmp-server/pom.xml
pom.xml

Change version in pom to prepare TAG 2.5.4

Pom change for tag 2.5.4

---

eplmp-core/pom.xml
eplmp-i18n/pom.xml
eplmp-server/eplmp-server-ear/pom.xml
eplmp-server/eplmp-server-ejb/pom.xml
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/DocumentManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/ProductManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerManagerBean.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerQueryBuilder.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/config/IndexerConfig.java
eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/util/IndicesUtils.java
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/common-template.json
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/document-template.json
eplmp-server/eplmp-server-ejb/src/main/resources/org/polarsys/eplmp/server/indexer/part-template.json
eplmp-server/eplmp-server-ext/pom.xml
eplmp-server/eplmp-server-office-doc/pom.xml
eplmp-server/eplmp-server-rest/pom.xml
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/DocumentResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/PartResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/DocumentBinaryResource.java
eplmp-server/eplmp-server-rest/src/main/java/org/polarsys/eplmp/server/rest/file/PartBinaryResource.java
eplmp-server/pom.xml
pom.xml

Prepare TAG 2.5.4

---

eplmp-core/pom.xml
eplmp-i18n/pom.xml
eplmp-server/eplmp-server-ear/pom.xml
eplmp-server/eplmp-server-ejb/pom.xml
eplmp-server/eplmp-server-ext/pom.xml
eplmp-server/eplmp-server-office-doc/pom.xml
eplmp-server/eplmp-server-rest/pom.xml
eplmp-server/pom.xml
pom.xml

Updated pom version to 2.5.5-SNAPSHOT

prepare 2.5.5-SNAPSHOT

---

eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/indexer/IndexerManagerBean.java

fix creation failed of workspace

indexer ES workspace creation resolved

---

eplmp-server/eplmp-server-ejb/src/main/java/org/polarsys/eplmp/server/PlatformHealthManagerBean.java

health troubles for postgres resolved

fix docdoku/docdoku-plm#1198
